In [39]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from statsmodels.formula.api import ols

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.preprocessing import StandardScaler

In [2]:
data=pd.read_csv('/Users/rickie/Desktop/statistics_by_python/car_sale.csv')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65 entries, 0 to 64
Data columns (total 10 columns):
券代码                65 non-null int64
日期                 65 non-null object
传统汽车销量             65 non-null float64
国内生产总值当季值(亿元)x1    65 non-null float64
汽油价格（元/吨）x2        65 non-null int64
人民币贷款基准利率%x3       65 non-null float64
汽车总产量（万辆）x4        65 non-null float64
公路里程数              64 non-null float64
汽车整车股票指数           65 non-null float64
消费者信心指数            65 non-null float64
dtypes: float64(7), int64(2), object(1)
memory usage: 5.2+ KB

In [5]:
data.head()

,券代码,日期,传统汽车销量,国内生产总值当季值(亿元)x1,汽油价格（元/吨）x2,人民币贷款基准利率%x3,汽车总产量（万辆）x4,公路里程数,汽车整车股票指数,消费者信心指数
0,65,2003年Q1,102.1,29825.5,3020,5.49,102.1,177.6375,1696.81,97.700000
1,64,2003年Q2,110.0,32537.3,3020,5.49,110.0,178.7550,1912.54,87.666667
2,63,2003年Q3,112.1,35291.9,2920,5.49,112.1,179.8725,1803.71,92.333333
3,62,2003年Q4,122.8,39767.4,3010,5.49,122.8,180.9900,1922.48,94.666667
4,61,2004年Q1,131.1,34544.6,3210,5.49,131.1,182.5125,1930.71,95.333333

In [17]:
data.columns=['id','date','sales','x1','x2','x3','x4','x5','x6','x7']
data

,id,date,sales,x1,x2,x3,x4,x5,x6,x7
0,65,2003年Q1,102.10,29825.5,3020,5.49,102.10,177.6375,1696.810,97.700000
1,64,2003年Q2,110.00,32537.3,3020,5.49,110.00,178.7550,1912.540,87.666667
2,63,2003年Q3,112.10,35291.9,2920,5.49,112.10,179.8725,1803.710,92.333333
3,62,2003年Q4,122.80,39767.4,3010,5.49,122.80,180.9900,1922.480,94.666667
4,61,2004年Q1,131.10,34544.6,3210,5.49,131.10,182.5125,1930.710,95.333333
5,60,2004年Q2,133.30,38700.8,3210,5.49,133.30,184.0350,1245.700,92.566667
6,59,2004年Q3,121.00,41855.0,3510,5.49,121.00,185.5575,1163.160,91.066667
7,58,2004年Q4,123.70,46739.8,3750,5.76,123.70,187.0800,870.610,92.566667
8,57,2005年Q1,139.70,40453.3,3750,5.76,139.70,188.5675,749.620,93.933333
9,56,2005年Q2,162.20,44793.1,4050,5.76,162.20,190.0550,764.840,94.533333
10,55,2005年Q3,139.30,48047.8,4100,5.76,139.30,191.5425,826.790,94.400000
11,54,2005年Q4,174.00,54024.8,4400,5.76,174.00,193.0300,796.800,93.866667
12,53,2006年Q1,185.90,47078.9,4400,5.76,185.90,231.1950,903.680,91.266667
13,52,2006年Q2,195.70,52673.3,4700,6.03,195.70,269.3600,1351.090,90.000000
14,51,2006年Q3,172.90,56064.7,4980,6.30,172.90,307.5250,1291.190,90.666667
15,50,2006年Q4,178.30,63621.6,4980,6.30,178.30,345.6900,1802.600,92.133333
16,49,2007年Q1,219.00,57159.3,4980,6.30,219.00,348.8575,2809.690,94.366667
17,48,2007年Q2,230.10,64781.6,4980,6.75,230.10,352.0250,3546.310,96.766667
18,47,2007年Q3,221.90,69482.1,4980,7.20,221.90,355.1925,5471.080,96.966667
19,46,2007年Q4,230.90,78669.3,4980,7.47,230.90,358.3600,4840.220,96.466667
20,45,2008年Q1,268.50,69373.6,5480,7.56,268.50,362.0250,3157.830,94.800000
21,44,2008年Q2,268.10,78711.8,5480,7.56,268.10,365.6900,1902.290,94.133333
22,43,2008年Q3,206.40,82460.1,6480,7.56,206.40,369.3550,1655.170,93.866667
23,42,2008年Q4,226.40,88699.0,6480,6.43,226.40,373.0200,1389.050,99.800000
24,41,2009年Q1,271.00,73979.2,5580,5.40,271.00,376.2875,2390.980,100.866667
25,40,2009年Q2,362.40,83865.8,5730,5.40,362.40,379.5550,3146.490,100.900000
26,39,2009年Q3,369.60,89846.9,6130,5.40,369.60,382.8225,3651.070,102.533333
27,38,2009年Q4,364.00,100825.8,6810,5.40,364.00,386.0900,5162.190,103.466667
28,37,2010年Q1,466.20,87501.3,7100,5.40,466.20,389.7650,4421.330,105.600000
29,36,2010年Q2,468.60,99347.4,7100,5.40,468.60,393.4400,3322.600,107.700000
...,...,...,...,...,...,...,...,...,...,...
35,30,2011年Q4,504.40,138012.1,8580,6.65,504.40,410.3900,2985.920,99.333333
36,29,2012年Q1,520.40,117357.6,8280,6.65,520.40,413.6975,3234.150,102.966667
37,28,2012年Q2,508.50,131320.6,918,6.65,508.50,417.0050,3162.540,102.166667
38,27,2012年Q3,481.40,138089.6,8320,6.15,481.40,420.3125,2799.050,99.466667
39,26,2012年Q4,551.60,151812.0,8840,6.15,551.60,423.6200,3464.190,104.966667
40,25,2013年Q1,574.80,129449.6,8530,6.15,575.10,426.6200,3520.890,105.100000
41,24,2013年Q2,653.90,143518.7,8520,6.15,654.20,429.6200,3562.360,99.900000
42,23,2013年Q3,478.00,152222.7,8225,6.15,478.40,432.6200,4046.070,98.266667
43,22,2013年Q4,747.20,167772.3,8550,6.15,748.00,435.6200,3997.140,101.366667
44,21,2014年Q1,659.10,140270.2,8535,6.15,659.80,438.2875,3873.020,104.033333
45,20,2014年Q2,660.80,155922.3,8640,6.15,662.20,440.9550,4020.070,103.933333
46,19,2014年Q3,600.80,164897.8,8980,6.15,602.60,443.6225,4703.210,104.533333
47,18,2014年Q4,557.70,180190.3,8200,6.15,561.40,446.2900,5227.650,104.900000
48,17,2015年Q1,689.20,150593.8,6775,6.00,691.90,449.0725,6580.570,107.533333
49,16,2015年Q2,649.10,167874.5,6670,5.50,653.70,451.8550,7016.610,107.666667
50,15,2015年Q3,587.40,175803.8,7235,5.00,593.80,454.6375,5438.900,104.700000
51,14,2015年Q4,517.40,191720.8,6410,4.75,536.80,457.4200,6461.440,103.866667
52,13,2016年Q1,656.54,160967.3,6105,4.75,662.34,460.4400,5617.758,102.800000
53,12,2016年Q2,624.19,179878.7,5965,4.75,635.39,463.4600,5749.814,101.233333
54,11,2016年Q3,640.24,189337.6,6570,4.75,652.14,466.4800,5850.480,105.666667
55,10,2016年Q4,815.23,209877.2,6420,4.75,837.03,469.5000,5785.150,108.066667
56,9,2017年Q1,707.44,179403.4,7120,4.75,713.04,471.4625,6095.690,110.933333
57,8,2017年Q2,514.52,199177.8,7025,4.75,528.42,473.4250,6105.308,112.900000
58,7,2017年Q3,804.54,209824.1,6685,4.75,824.84,475.3875,6721.655,115.966667
59,6,2017年Q4,852.48,232349.0,7240,4.75,890.38,477.3500,6276.352,122.600000
60,5,2018年Q1,731.60,197920.0,7725,4.75,745.90,479.1750,5916.325,122.866667
61,4,2018年Q2,648.78,219295.4,7780,4.75,675.68,481.0000,5312.501,121.333333
62,3,2018年Q3,616.02,229495.5,8265,4.75,646.92,482.8250,4877.138,118.933333
63,2,2018年Q4,694.33,253598.6,8755,4.75,747.83,484.6500,4227.437,121.400000
64,1,2019年Q1,592.43,213432.8,7240,4.75,633.60,NaN,4661.423,123.700000

In [21]:
formula="sales~x1+x2"
model=ols(formula,data).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.874
Model:                            OLS   Adj. R-squared:                  0.870
Method:                 Least Squares   F-statistic:                     214.7
Date:                Wed, 05 Feb 2020   Prob (F-statistic):           1.35e-28
Time:                        20:34:43   Log-Likelihood:                -375.59
No. Observations:                  65   AIC:                             757.2
Df Residuals:                      62   BIC:                             763.7
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -39.8319     34.341     -1.160      0.251    -108.479      28.815
x1             0.0029      0.000     12.692      0.000       0.002       0.003
x2             0.0199      0.007      2.725      0.008       0.005       0.035
==============================================================================
Omnibus:                        0.186   Durbin-Watson:                   1.460
Prob(Omnibus):                  0.911   Jarque-Bera (JB):                0.379
Skew:                          -0.057   Prob(JB):                        0.827
Kurtosis:                       2.644   Cond. No.                     4.61e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.61e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [35]:
X=data[['x1','x2']]
y=data['sales']
std=StandardScaler()
X=std.fit_transform(X)

/Users/rickie/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/Users/rickie/anaconda3/lib/python3.7/site-packages/sklearn/base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)

In [48]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)
lg=LinearRegression()
lg.fit(X_train,y_train)
print('coefficients:',lg.coef_)
print('intercept:',lg.intercept_)
lg.score(X_test,y_test)

coefficients: [168.87571735  44.52606071]
intercept: 420.359857233643

0.8438819080157373

In [49]:
np.mean(cross_val_score(lg,X_train,y_train,cv=5))

0.8200299467722854

In [50]:
lg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)